version: "3.7"

networks:

  default:
    name: "elasticapm-net"
    driver: "bridge"

services:

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.17.3"
    container_name: "elasticsearch"
    environment:
      - "ES_JAVA_OPTS=-Xmx256m -Xms256m"
      - "ELASTIC_PASSWORD=bozklPbQN234mlwerVyVermUROQ*"
    ulimits:
      memlock:
        hard: -1
        soft: -1
    volumes:
      - "./elasticsearch/config.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro"
      - "elasticsearch-data:/usr/share/elasticsearch/data"
    ports:
      - "9200:9200"
    healthcheck:
      interval: "20s"
      retries: 10
      test: "curl -s http://localhost:9200/_cluster/health | grep -vq '\"status\":\"red\"'"

  kibana:
    image: "docker.elastic.co/kibana/kibana:7.17.3"
    container_name: "kibana"
    depends_on:
      elasticsearch:
        condition: "service_healthy"
    volumes:
      - "./kibana/config.yml:/usr/share/kibana/config/kibana.yml:ro"
    ports:
      - "5601:5601"
    healthcheck:
      interval: "10s"
      retries: 20
      test: "curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null -u elastic:bozklPbQN234mlwerVyVermUROQ* http://localhost:5601/api/status"

  apm-server:
    image: "docker.elastic.co/apm/apm-server:7.17.3"
    container_name: "apm-server"
    depends_on:
      elasticsearch:
        condition: "service_healthy"
      kibana:
        condition: "service_healthy"
    volumes:
      - "./apm-server/config.yml:/usr/share/apm-server/apm-server.yml:ro"
    ports:
      - "8200:8200"
    command:
      - "apm-server"
      - "--strict.perms=false"
      - "-e"
    healthcheck:
      interval: "10s"
      retries: 12
      test: "curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:8200/"

  dotnetcore-api:
    image: "${DOCKER_REGISTRY-}dotnetcore-api"
    build:
      context: "./dotnetcore-api"
      dockerfile: "Dockerfile"
    container_name: "dotnetcore-api"
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy
      apm-server:
        condition: service_healthy
    volumes:
      - "./dotnetcore-api/.logs:/app/logs"
    ports:
      - "8181:8181"

  filebeat-dotnetcore-api:
    image: "docker.elastic.co/beats/filebeat:7.17.3"
    container_name: "filebeat-dotnetcore-api"
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy
    volumes:
      - "./filebeat-dotnetcore-api/config.yml:/usr/share/filebeat/filebeat.yml:ro"
      - "./dotnetcore-api/.logs:/usr/share/services/dotnetcore-api/logs"
    command:
      - "filebeat"
      - "--strict.perms=false"
      - "-e"

volumes:

  elasticsearch-data:
    driver: local
