version: '2.2'

networks:
  default:
    name: "elasticapm-net"
    driver: "bridge"

services:
  fleet:
    image: docker.elastic.co/beats/elastic-agent:${STACK_VERSION}
    user: root # note, synthetic browser monitors require this set to `elastic-agent`
    container_name: fleet
    volumes:
      - certs:/usr/share/elastic-agent/config/certs
      - ./fleet/fleet.yml:/usr/share/elastic-agent/fleet.yml
    environment:
      - ELASTICSEARCH_CA=/usr/share/elastic-agent/config/certs/ca/ca.crt
#      - KIBANA_CA=/usr/share/elastic-agent/config/certs/ca/ca.crt
      - ELASTICSEARCH_HOST=https://es01:9200
#      - KIBANA_HOST=https://kibana:5601
#      - KIBANA_FLEET_SETUP=1
#      - KIBANA_FLEET_HOST=https://kibana:5601
#      - FLEET_ENROLLMENT_TOKEN=${ENROLLMENT_TOKEN}
#      - FLEET_ENROLL=1
      - FLEET_CA=/usr/share/elastic-agent/config/certs/ca/ca.crt
      - FLEET_URL=https://localhost:8220
      - FLEET_SERVER_ENABLE=true
      - FLEET_SERVER_ELASTICSEARCH_HOST=https://es01:9200
      - FLEET_SERVER_SERVICE_TOKEN=${SERVICE_TOKEN}
      - FLEET_SERVER_POLICY_ID=${FLEET_SERVER_POLICY_ID}
      - FLEET_SERVER_POLICY=fleet-server-policy
      - FLEET_SERVER_CERT=/usr/share/elastic-agent/config/certs/fleet/fleet.crt
      - FLEET_SERVER_CERT_KEY=/usr/share/elastic-agent/config/certs/fleet/fleet.key
    ports:
      - 8220:8220
      - 6791:6791
    restart: on-failure
    healthcheck:
      interval: 10s
      retries: 12
      test: "curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:8200/"

volumes:
  certs:
    driver: local