cluster.name: "docker-cluster"
cluster.routing.allocation.disk.threshold_enabled: false

network.host: 0.0.0.0

discovery.type: single-node

bootstrap.memory_lock: true

xpack.license.self_generated.type: trial
xpack.security.enabled: true
xpack.monitoring.collection.enabled: true
xpack.security.authc.api_key.enabled: true
xpack.security.authc.token.enabled: true